// dotproduct is a CSV-driven end-to-end runner for the three two-party
// MK-BFV computation scenarios (see mkbfv/scenarios.go for the protocols):
//
//	scenario 1 (weighted sum):
//	  P1 CSV: header d1..dK, one int64 row per record
//	  P2 CSV: header w1..wK, a single int64 row
//	  out  :  res[i] = sum_k dk[i]*wk
//	scenario 2 (row-wise weighted sum):
//	  P2 CSV: header w1..wK, one int64 row per record
//	  out  :  res[i] = sum_k dk[i]*wk[i]
//	scenario 3 (sum-product):
//	  P2 CSV: header w1..wK, one int64 row per record
//	  out  :  res[i] = prod_k (dk[i]+wk[i])
//
// The whole protocol (both parties + evaluator) is simulated sequentially in
// this one process; per-phase timings and communication volume are printed.
// By default both parameter sets (pn14, pn15) are executed sequentially;
// results go to data/res_s<scenario>_<conf>.csv unless -out overrides.
//
// Usage examples:
//
//	# generate deterministic test data (100k rows) into dotproduct/data
//	go run ./dotproduct -gen                    # scenario 1 (weights row)
//	go run ./dotproduct -gen -scenario 3        # full P2 columns, small bound
//
//	# run one scenario on all parameter sets, verify, write result CSVs
//	go run ./dotproduct -scenario 2
//
//	# single parameter set (pn15 needs ~4.5 GB RAM; recommended GOGC>=400)
//	GOGC=400 go run ./dotproduct -scenario 1 -conf pn15
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"math/big"
	"math/rand"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"mk-lattigo/mkbfv"
)

const genK = 5 // columns/weights generated by -gen

func main() {
	var (
		scenario = flag.Int("scenario", 1, "computation scenario: 1 = weighted sum (P2 holds K scalars), 2 = row-wise weighted sum (P2 holds K columns), 3 = product (d1+w1)*...*(dK+wK)")
		p1csv    = flag.String("p1", "data/p1_data.csv", "P1 data CSV (header d1..dK, one row per record)")
		p2csv    = flag.String("p2", "", "P2 input CSV (default: data/p2_weights.csv for scenario 1, data/p2_data.csv otherwise)")
		out      = flag.String("out", "", "result CSV (default: data/res_s<scenario>_<conf>.csv)")
		conf     = flag.String("conf", "all", "parameter set: pn14 | pn15 | all")
		tmin     = flag.Uint64("tmin", 0, "minimum plaintext modulus T (0 = derive from data range)")
		verify   = flag.Bool("verify", true, "verify decrypted result against plaintext computation")
		reps     = flag.Int("reps", 1, "repeat the full protocol N times")

		gen    = flag.Bool("gen", false, "generate deterministic test CSVs and exit")
		gendir = flag.String("gendir", "data", "directory for generated CSVs")
		rows   = flag.Int("rows", 100000, "generated rows per column")
		bound  = flag.Int64("bound", 0, "generated |d|,|w| bound (0 = scenario default: 2^20 for 1/2, 512 for 3)")
		seed   = flag.Int64("seed", 0xC0FFEE, "PRNG seed for -gen")
	)
	flag.Parse()

	if *bound == 0 {
		if *scenario == mkbfv.ScenarioSumProduct {
			*bound = 512 // keep 4*(2*bound)^K <= Q[0] ~ 2^53 for K=5
		} else {
			*bound = 1 << 20
		}
	}

	if *gen {
		if err := genData(*gendir, *scenario, *rows, *bound, *seed); err != nil {
			fmt.Fprintln(os.Stderr, "gen:", err)
			os.Exit(1)
		}
		return
	}

	if *scenario != mkbfv.ScenarioWeightedSum &&
		*scenario != mkbfv.ScenarioWeightedSumRowwise &&
		*scenario != mkbfv.ScenarioSumProduct {
		fmt.Fprintf(os.Stderr, "unknown -scenario %d (want 1, 2 or 3)\n", *scenario)
		os.Exit(1)
	}

	// -------- read inputs --------
	_, dCols, err := readIntCSV(*p1csv)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read p1:", err)
		os.Exit(1)
	}
	k := len(dCols)
	if k == 0 || len(dCols[0]) == 0 {
		fmt.Fprintln(os.Stderr, "empty P1 data")
		os.Exit(1)
	}
	records := len(dCols[0])

	p2path := *p2csv
	if p2path == "" {
		if *scenario == mkbfv.ScenarioWeightedSum {
			p2path = "data/p2_weights.csv"
		} else {
			p2path = "data/p2_data.csv"
		}
	}
	_, wCols, err := readIntCSV(p2path)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read p2:", err)
		os.Exit(1)
	}

	var ws []int64
	var wdata [][]int64
	switch *scenario {
	case mkbfv.ScenarioWeightedSum:
		if len(wCols) != k || len(wCols[0]) != 1 {
			fmt.Fprintf(os.Stderr, "%s: scenario 1 needs exactly one row with %d values (w1..w%d)\n", p2path, k, k)
			os.Exit(1)
		}
		ws = make([]int64, k)
		for c := range ws {
			ws[c] = wCols[c][0]
		}
	default:
		if len(wCols) != k {
			fmt.Fprintf(os.Stderr, "%s: scenario %d needs %d columns (w1..w%d)\n", p2path, *scenario, k, k)
			os.Exit(1)
		}
		for c := range wCols {
			if len(wCols[c]) != records {
				fmt.Fprintf(os.Stderr, "%s: column w%d has %d rows, P1 data has %d\n", p2path, c+1, len(wCols[c]), records)
				os.Exit(1)
			}
		}
		wdata = wCols
	}

	// -------- derive plaintext modulus from the actual value range --------
	maxD := colAbsMax(dCols)
	maxW := colAbsMax(wCols)
	if *tmin == 0 {
		if *scenario == mkbfv.ScenarioSumProduct {
			*tmin = mkbfv.MinTSumProduct(k, maxD, maxW)
		} else {
			*tmin = mkbfv.MinT(k, maxD, maxW)
		}
	}
	T := mkbfv.FindPrimeT(*tmin)

	confs, err := confList(*conf)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("scenario: %d (%s)\n", *scenario, mkbfv.ScenarioName(*scenario))
	fmt.Printf("inputs : %s x %d records, K=%d | P2: %s\n", *p1csv, records, k, p2path)
	fmt.Printf("range  : |d|max=%d |w|max=%d -> T=%d (%d bits) | params: %s\n\n",
		maxD, maxW, T, big.NewInt(0).SetUint64(T).BitLen(), strings.Join(confs, ","))

	for _, name := range confs {
		lit := literalFor(name)
		if T > lit.Q[0] {
			if *scenario == mkbfv.ScenarioSumProduct {
				fmt.Fprintf(os.Stderr,
					"data range too large for %s (scenario %d): need T>=%d but lattigo requires T<=Q[0]=%d\n"+
						"(K=%d, |d|max=%d, |w|max=%d: bound 4*(|d|max+|w|max)^K exceeds the modulus);\n"+
						"reduce values/bound or split into CRT limbs (x3 cost)\n",
					name, *scenario, T, lit.Q[0], k, maxD, maxW)
			} else {
				fmt.Fprintf(os.Stderr,
					"data range too large for %s: need T>=%d but lattigo requires T<=Q[0]=%d\n"+
						"(|d|max=%d, |w|max=%d, K=%d); reduce values or split into CRT limbs (x3 cost)\n",
					name, T, lit.Q[0], maxD, maxW, k)
			}
			os.Exit(1)
		}
		lit.T = T

		outPath := *out
		if outPath == "" {
			outPath = fmt.Sprintf("data/res_s%d_%s.csv", *scenario, name)
		} else if len(confs) > 1 {
			ext := filepath.Ext(outPath)
			outPath = strings.TrimSuffix(outPath, ext) + "_" + name + ext
		}

		var res []int64
		for r := 1; r <= *reps; r++ {
			if *reps > 1 {
				fmt.Printf("========== params=%s run %d/%d ==========\n", name, r, *reps)
			} else {
				fmt.Printf("========== params=%s ==========\n", name)
			}
			t0 := time.Now()
			params := mkbfv.NewParametersFromLiteral(lit)
			st := &mkbfv.DotProductStats{CRSTime: time.Since(t0), Verbose: true}
			switch *scenario {
			case mkbfv.ScenarioWeightedSum:
				res = mkbfv.RunWeightedSum(params, dCols, ws, *verify, st)
			case mkbfv.ScenarioWeightedSumRowwise:
				res = mkbfv.RunWeightedSumRowwise(params, dCols, wdata, *verify, st)
			case mkbfv.ScenarioSumProduct:
				res = mkbfv.RunSumProduct(params, dCols, wdata, *verify, st)
			}
			st.Print()
		}

		if !*verify {
			fmt.Println("note: -verify=false, result not checked")
		}
		if err := writeResultCSV(outPath, res); err != nil {
			fmt.Fprintln(os.Stderr, "write out:", err)
			os.Exit(1)
		}
		fmt.Printf("result written to %s (%d rows)\n", outPath, len(res))
	}
}

// confList expands the -conf flag into an ordered list of parameter-set names.
func confList(conf string) ([]string, error) {
	switch conf {
	case "pn14":
		return []string{"pn14"}, nil
	case "pn15":
		return []string{"pn15"}, nil
	case "all":
		return []string{"pn14", "pn15"}, nil
	default:
		return nil, fmt.Errorf("unknown -conf %s (want pn14 | pn15 | all)", conf)
	}
}

func literalFor(name string) mkbfv.ParametersLiteral {
	switch name {
	case "pn14":
		return mkbfv.PN14QP439
	default: // "pn15"
		return mkbfv.PN15QP660
	}
}

// colAbsMax returns the largest |value| across all columns.
func colAbsMax(cols [][]int64) int64 {
	m := int64(0)
	for _, col := range cols {
		for _, v := range col {
			if v > m {
				m = v
			} else if -v > m {
				m = -v
			}
		}
	}
	return m
}

// readIntCSV reads a CSV whose first row is a header and whose remaining rows
// hold integers; it returns the header and the data column-wise.
func readIntCSV(path string) (header []string, cols [][]int64, err error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()

	rd := csv.NewReader(f)
	rd.FieldsPerRecord = -1
	rows, err := rd.ReadAll()
	if err != nil {
		return nil, nil, err
	}
	if len(rows) < 2 {
		return nil, nil, fmt.Errorf("%s: need a header row and at least one data row", path)
	}
	n := len(rows) - 1
	cols = make([][]int64, len(rows[0]))
	for c := range cols {
		cols[c] = make([]int64, 0, n)
	}
	for _, row := range rows[1:] {
		if len(row) != len(rows[0]) {
			return nil, nil, fmt.Errorf("%s: ragged row %q", path, row)
		}
		for c, field := range row {
			v, err := strconv.ParseInt(field, 10, 64)
			if err != nil {
				return nil, nil, fmt.Errorf("%s: %q: %v", path, field, err)
			}
			cols[c] = append(cols[c], v)
		}
	}
	return rows[0], cols, nil
}

func writeResultCSV(path string, res []int64) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := csv.NewWriter(f)
	if err := w.Write([]string{"res"}); err != nil {
		return err
	}
	for _, v := range res {
		if err := w.Write([]string{strconv.FormatInt(v, 10)}); err != nil {
			return err
		}
	}
	w.Flush()
	return w.Error()
}

// genData writes deterministic P1/P2 test CSVs: d1..dK with `rows` records in
// [-bound, bound). P2's file depends on the scenario: a single w1..wK row
// (scenario 1) or full w1..wK columns (scenarios 2/3).
func genData(dir string, scenario, rows int, bound int64, seed int64) error {
	k := genK
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	rng := rand.New(rand.NewSource(seed))

	p1h := make([]string, k)
	p2h := make([]string, k)
	for c := range p1h {
		p1h[c] = "d" + strconv.Itoa(c+1)
		p2h[c] = "w" + strconv.Itoa(c+1)
	}

	f, err := os.Create(filepath.Join(dir, "p1_data.csv"))
	if err != nil {
		return err
	}
	w := csv.NewWriter(f)
	w.Write(p1h)
	row := make([]string, k)
	for i := 0; i < rows; i++ {
		for c := 0; c < k; c++ {
			row[c] = strconv.FormatInt(rng.Int63n(2*bound)-bound, 10)
		}
		w.Write(row)
	}
	w.Flush()
	if err := w.Error(); err != nil {
		f.Close()
		return err
	}
	f.Close()

	if scenario == mkbfv.ScenarioWeightedSum {
		f, err = os.Create(filepath.Join(dir, "p2_weights.csv"))
		if err != nil {
			return err
		}
		w = csv.NewWriter(f)
		w.Write(p2h)
		for c := 0; c < k; c++ {
			row[c] = strconv.FormatInt(rng.Int63n(2*bound)-bound, 10)
		}
		w.Write(row)
		w.Flush()
		err = w.Error()
		f.Close()
		if err != nil {
			return err
		}
		fmt.Printf("generated %s (rows=%d, K=%d, |d|,|w|<%d) and %s (single row) for scenario 1\n",
			filepath.Join(dir, "p1_data.csv"), rows, k, bound, filepath.Join(dir, "p2_weights.csv"))
		return nil
	}

	f, err = os.Create(filepath.Join(dir, "p2_data.csv"))
	if err != nil {
		return err
	}
	w = csv.NewWriter(f)
	w.Write(p2h)
	for i := 0; i < rows; i++ {
		for c := 0; c < k; c++ {
			row[c] = strconv.FormatInt(rng.Int63n(2*bound)-bound, 10)
		}
		w.Write(row)
	}
	w.Flush()
	err = w.Error()
	f.Close()
	if err != nil {
		return err
	}
	fmt.Printf("generated %s and %s (rows=%d, K=%d, |d|,|w|<%d) for scenario %d\n",
		filepath.Join(dir, "p1_data.csv"), filepath.Join(dir, "p2_data.csv"), rows, k, bound, scenario)
	return nil
}
